spring:
  application:
    name: spring-cloud-sleuth-pay
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      # 采样率 范围 0~1 ，1表示全部采集
      probability: 1
server:
  port: 10012

eureka:
  instance:
    instance-id: spring-cloud-sleuth-pay
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #单机
      defaultZone: http://eureka1:7001/eureka
      #集群
#      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka,http://eureka3:7003/eureka
  server:
    eureka.server.enable-self-preservation: false