spring:
  application:
    name: spring-cloud-pay
server:
  port: 10003
eureka:
  instance:
    instance-id: spring-cloud-pay02
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #单机
      defaultZone: http://eureka1:7001/eureka
      #集群
#      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka,http://eureka3:7003/eureka
  server:
    eureka.server.enable-self-preservation: false